jwt:
    issuer: twgearlgrey@gmail.com
    secret: RL0daTgJz3h4AdFlVOMYktn7V6uScGTT
logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security:  debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: '!Q2w3e4r'
        url: jdbc:mysql://52.79.237.168:3306/Jboard
        username: java
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                user_sql_comment: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/
        restart:
            enabled: true
    servlet:
        multipart:
            location: src/main/resources/static/file
            max-file-size: 10MB
